version: "3"
services:
  SonarQube:
    image: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/SonarQube/data
      - sonarqube_extensions:/opt/SonarQube/extensions
      - sonarqube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:6.2.6
    command:
    - --loglevel warning
    volumes:
    - redis-data:/data:Z

  postgresql:
    restart: always
    image: sameersbn/postgresql:12-20200524
    volumes:
    - postgresql-git-data:/var/lib/postgresql:Z
    environment:
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${DB_NAME}
    - DB_EXTENSION=${DB_EXTENSION}

  gitlab:
    restart: always
    image: sameersbn/gitlab:15.8.0
    depends_on:
    - redis
    - postgresql
    ports:
    - "8080:80"
    - "2222:22"
    volumes:
    - gitlab-data:/home/git/data:Z
    environment:
    - DEBUG=${DEBUG}
    - DB_ADAPTER=${DB_ADAPTER}
    - DB_HOST=${DB_HOST}
    - DB_PORT=${DB_PORT}
    - DB_USER=${DB_USER}
    - DB_PASS=${DB_PASS}
    - DB_NAME=${DB_NAME}
    - REDIS_HOST=${REDIS_HOST}
    - REDIS_PORT=${REDIS_PORT}
    - TZ=${TZ}
    - GITLAB_TIMEZONE=${GITLAB_TIMEZONE}
    - GITLAB_HTTPS=${GITLAB_HTTPS}
    - SSL_SELF_SIGNED=${SSL_SELF_SIGNED}
    - GITLAB_HOST=${GITLAB_HOST}
    - GITLAB_SSH_PORT=${GITLAB_SSH_PORT}
    - GITLAB_SECRETS_DB_KEY_BASE=${GITLAB_SECRETS_DB_KEY_BASE}
    - GITLAB_SECRETS_SECRET_KEY_BASE=${GITLAB_SECRETS_SECRET_KEY_BASE}
    - GITLAB_SECRETS_OTP_KEY_BASE=${GITLAB_SECRETS_OTP_KEY_BASE}
    - GITLAB_ROOT_PASSWORD=${GITLAB_ROOT_PASSWORD}
    - GITLAB_ROOT_EMAIL=${GITLAB_ROOT_EMAIL}
    - GITLAB_NOTIFY_ON_BROKEN_BUILDS=${GITLAB_NOTIFY_ON_BROKEN_BUILDS}
    - GITLAB_NOTIFY_PUSHER=${GITLAB_NOTIFY_PUSHER}
    - GITLAB_EMAIL=${GITLAB_EMAIL}
    - GITLAB_EMAIL_REPLY_TO=${GITLAB_EMAIL_REPLY_TO}
    - GITLAB_INCOMING_EMAIL_ADDRESS=${GITLAB_INCOMING_EMAIL_ADDRESS}
    - GITLAB_BACKUP_SCHEDULE=${GITLAB_BACKUP_SCHEDULE}
    - GITLAB_BACKUP_TIME=${GITLAB_BACKUP_TIME}
    - SMTP_ENABLED=${SMTP_ENABLED}
    - SMTP_DOMAIN=${SMTP_DOMAIN}
    - SMTP_HOST=${SMTP_HOST}
    - SMTP_PORT=${SMTP_PORT}
    - SMTP_USER=${SMTP_USER}
    - SMTP_PASS=${SMTP_PASS}
    - SMTP_STARTTLS=${SMTP_STARTTLS}
    - SMTP_AUTHENTICATION=${SMTP_AUTHENTICATION}
    - IMAP_ENABLED=${IMAP_ENABLED}
    - IMAP_HOST=${IMAP_HOST}
    - IMAP_PORT=${IMAP_PORT}
    - IMAP_USER=${IMAP_USER}
    - IMAP_PASS=${IMAP_PASS}
    - IMAP_SSL=${IMAP_SSL}
    - IMAP_STARTTLS=${IMAP_STARTTLS}
    - OAUTH_ENABLED=${OAUTH_ENABLED}
    - OAUTH_AUTO_SIGN_IN_WITH_PROVIDER=${OAUTH_AUTO_SIGN_IN_WITH_PROVIDER}
    - OAUTH_ALLOW_SSO=${OAUTH_ALLOW_SSO}
    - OAUTH_BLOCK_AUTO_CREATED_USERS=${OAUTH_BLOCK_AUTO_CREATED_USERS}
    - OAUTH_AUTO_LINK_LDAP_USER=${OAUTH_AUTO_LINK_LDAP_USER}
    - OAUTH_AUTO_LINK_SAML_USER=${OAUTH_AUTO_LINK_SAML_USER}
    - OAUTH_CAS3_LABEL=${OAUTH_CAS3_LABEL}
    - OAUTH_CAS3_DISABLE_SSL_VERIFICATION=${OAUTH_CAS3_DISABLE_SSL_VERIFICATION}
    - OAUTH_CAS3_LOGIN_URL=${OAUTH_CAS3_LOGIN_URL}
    - OAUTH_CAS3_VALIDATE_URL=${OAUTH_CAS3_VALIDATE_URL}
    - OAUTH_CAS3_LOGOUT_URL=${OAUTH_CAS3_LOGOUT_URL}
    - OAUTH_SAML_LABEL=${OAUTH_SAML_LABEL}
    - OAUTH_SAML_NAME_IDENTIFIER_FORMAT=${OAUTH_SAML_NAME_IDENTIFIER_FORMAT}

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

  redis-data:
  postgresql-git-data:
  gitlab-data:
