---
version: '3'
services:
  bitwarden:
    container_name: bitwarden
    image: bitwardenrs/server
    restart: always
    ports:
      - 8010:80
    volumes:
      - bw-data:/data
    environment:
      WEBSOCKET_ENABLED: 'true' # Required to use websockets
      SIGNUPS_ALLOWED: 'true'   # set to false to disable signups
volumes:
  bw-data:
networks:
  default:
    external: true
    name: cicd
