---
version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - 8090:8080
#      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      # - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/local/bin/docker:/usr/local/bin/docker
volumes:
  jenkins_home:
networks:
  default:
    external: true
    name: cicd
