version: "3"
services:
  SonarQube:
    image: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/${POSTGRES_DB}
      SONAR_JDBC_USERNAME: ${POSTGRES_USER}
      SONAR_JDBC_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - sonarqube_data:/opt/SonarQube/data
      - sonarqube_extensions:/opt/SonarQube/extensions
      - sonarqube_logs:/opt/SonarQube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

  gitlab-postgresql:
    hostname: 'gitlab-postgresql-db'
    image: postgres:12
    environment:
      POSTGRES_DB: "gitlabhq_production"
      POSTGRES_USER: "gitlab"
      POSTGRES_PASSWORD: "gitlab"
      POSTGRES_HOST_AUTH_METHOD: "trust" 
    volumes:
    - git_postgresql_data:/var/lib/postgresql
    networks:
      - gitlab

  gitlab:
    image: 'gitlab/gitlab-ce:15.8.0-ce.0'
    restart: always
    hostname: 'gitlab-docker'
    container_name: gitlab
    depends_on:
    - gitlab-postgresql
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        postgresql['enable'] = false
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_host'] = 'gitlab-postgresql-db'
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'gitlab' 
        gitlab_rails['db_database'] = "gitlabhq_production"
    ports:
      - '9000:80'
      - '8443:443'
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab
    networks:
      - gitlab

  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    container_name: gitlab-runner    
    restart: always
    depends_on:
      - gitlab
    volumes:
      - gitlab_runner:/etc/gitlab-runner
    networks:
      - gitlab

networks:
  gitlab:
    name: gitlab-network

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:

  gitlab_config:
  gitlab_data:
  gitlab_logs:
  git_postgresql_data:
  gitlab_runner:
