---
version: '3.7'
services:
  mongodb1:
    container_name: mongodb1
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb1_data:/data/db
  mongodb2:
    container_name: mongodb2
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27018:27017
    volumes:
      - mongodb2_data:/data/db
  mongodb3:
    container_name: mongodb3
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27019:27017
    volumes:
      - mongodb3_data:/data/db
volumes:
  mongodb1_data:
  mongodb2_data:
  mongodb3_data:
networks:
  default:
    external: true
    name: cicd
