---
- name: Update SSL certificate for 2021 Sep expiry by LetsEncrypt Root CA
  apt:
    name: "libgnutls-openssl27"
    state: latest

- name: Ensure the APT cache is up to date
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Setup Language package
  shell: locale-gen en_US.UTF-8

- name: Install common packages
  apt:
    name: "{{ item }}"
  with_items: "{{ common_packages }}"
