---
- name: Set hostname
  become: yes
  hostname:
    name: "{{ hostname }}"

- name: Copy /etc/hosts file
  copy:
    src: "hosts"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
